### ISSUE TITLE
githubの使い方

### ISSUE THREAD

**Issue by KinoshitaRiku** [KinoshitaRiku/laravel#1]
githubの有効な使い方が理解できてない。
どの粒度でcommitしていけばいいから不明。
一人だからmainでpushしている現状だが、branchはしたほうが良いのか？

**Comment by shingo8422** [comment]
機能単位ごとに、developからfeatureブランチ派生させて、
developをマージ先として、PullRequestを出して、
ソロ疑似チーム開発みたいなのはしてみてもいいかも
